version: '3'

# @todo allow these to be overridden or document them as required folder
# structures. See also config/phpcs.xml and config/phpstan.neon
vars:
  YAML_DIRS: 'web/**/*.yml'
  TWIG_DIRS: 'web/modules web/profiles web/themes'
  TEST_DIRS: 'web/modules/custom web/themes/custom web/sites'
  NIGHTWATCH_TEST_DIRS: 'test'
  FUNC_ENSURE_DIRS: |
    DIRS_ARR=({{.TEST_DIRS}})
    for DIR in "${DIRS_ARR[@]}"; do
      mkdir -p $DIR
    done

tasks:
  static:
    desc: Runs all static tests
    deps: [security, lint, phpstan, phpunit, phpcs]
  functional:
    desc: Runs all tests that require a bootstrapped Drupal site
    deps: [config, nightwatch]
  security:
    desc: Runs security checks for composer packages and Drupal contrib
    cmds:
      - ./vendor/bin/local-php-security-checker
      - ./vendor/bin/drush pm:security
  lint:
    desc: Runs lint on composer, YAML, and Twig files
    cmds:
      - echo {{.YAML_DIRS}}
      - composer validate
      - |
        DIRS_ARR=({{.YAML_DIRS}})
        for DIR in "${DIRS_ARR[@]}"; do
          ./vendor/bin/yaml-lint $DIR
        done
      - |
        DIRS_ARR=({{.TWIG_DIRS}})
        for DIR in "${DIRS_ARR[@]}"; do
          ./vendor/bin/drainpipe-twig-linter lint $DIR
        done
  config:
    desc: Verifies that exported config matches the config in Drupal
    cmds:
      - if [ $(./vendor/bin/drush config:status --format=string | wc -w) -gt 0 ]; then echo "Config export does not match"; drush config:status; exit 1; fi
  phpstan:
    dec: Runs PHPStan with mglaman/phpstan-drupal
    cmds:
      - ./vendor/bin/phpstan analyse -c vendor/lullabot/drainpipe-dev/config/phpstan.neon {{.TEST_DIRS}}
  phpunit:
    desc: Runs PHPUnit
    cmds:
      - |
        {{ .FUNC_ENSURE_DIRS }}
      - ./vendor/bin/phpunit {{.TEST_DIRS}}
  phpcs:
    desc: Runs PHPCS with Drupal Coding Standards
    cmds:
      - |
        {{ .FUNC_ENSURE_DIRS }}
      - ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
      - ./vendor/bin/phpcs --standard=vendor/lullabot/drainpipe-dev/config/phpcs.xml {{.TEST_DIRS}}
  autofix:
    desc: Runs PHPCBF with Drupal Coding Standards to fix PHPCS violations
    cmds:
      - |
        {{ .FUNC_ENSURE_DIRS }}
      - ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
      - ./vendor/bin/phpcbf --standard=vendor/lullabot/drainpipe-dev/config/phpcs.xml {{.TEST_DIRS}}
  nightwatch:
    desc: Runs Nighwatch functional browser tests
    env:
      NIGHTWATCH_ENV: 'firefox,chrome'
    cmds:
      - yarn
      - yarn nightwatch --env $NIGHTWATCH_ENV
